#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FREQUENCE_ECHANTILLONNAGE 44100

// Waveform
#define WAVEFORM_WIDTH  1500
#define WAVEFORM_MAX_PERIOD 2.0
#define WAVEFORM_MIN_PERIOD 0.001
#define AUTO_ADJUST_NUMBER_OF_PERIODS 2

// Spectrum
#define SPECTRUM_NUMBER_OF_OCTAVES 6
#define SPECTRUM_NUMBER_OF_BARS (SPECTRUM_NUMBER_OF_OCTAVES * 12 - 2)
#define SPECTRUM_MARGIN 4
#define SPECTRUM_TIME_CONSTANT 45
#define SPECTRUM_IGNORE_PIXELS 6

#define SPECTRUM_PM_MARGIN  15
#define SPECTRUM_PM_SPACE   30
#define SPECTRUM_PM_BOXSIZE 20

// Filter
#define FILTER_MAX_GAIN_PERCENTAGE 120

// Musique
#define NOTES_START_FREQUENCY 110

// Sampler
#define SAMPLER_SAMPLES_PER_INSTRUMENT 3
#define SAMPLER_NUMBER_OF_INSTRUMENTS 3

#endif // CONSTANTS_H

